//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Resources.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქალაქი არ არსებობს.
        /// </summary>
        internal static string CityDoesn_tExist {
            get {
                return ResourceManager.GetString("CityDoesn\'tExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კონტაქტის ტიპი არ არის ვალიდური.
        /// </summary>
        internal static string ContactTypeIsNotValid {
            get {
                return ResourceManager.GetString("ContactTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი არ არის ვალიდური.
        /// </summary>
        internal static string FirstNameIsNotValid {
            get {
                return ResourceManager.GetString("FirstNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სქესი არ არის ვალიდური.
        /// </summary>
        internal static string GenderIsNotValid {
            get {
                return ResourceManager.GetString("GenderIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი არ არის ვალიდური.
        /// </summary>
        internal static string IdentityNumberIsNotValid {
            get {
                return ResourceManager.GetString("IdentityNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი არ არის ვალიდური.
        /// </summary>
        internal static string LastNameIsNotValid {
            get {
                return ResourceManager.GetString("LastNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნომერი არ არის ვალიდური.
        /// </summary>
        internal static string NumberIsNotValid {
            get {
                return ResourceManager.GetString("NumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არ არის სრულწლოვანი.
        /// </summary>
        internal static string PersonIsNotAdult {
            get {
                return ResourceManager.GetString("PersonIsNotAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაკავშირებული ადამიანი არ იძებნება.
        /// </summary>
        internal static string RelatedPersonDoesn_tExist {
            get {
                return ResourceManager.GetString("RelatedPersonDoesn\'tExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაკავშირებული პერსონის ტიპი არ არის ვალიდური.
        /// </summary>
        internal static string ReletivePersonTypeIsNotValid {
            get {
                return ResourceManager.GetString("ReletivePersonTypeIsNotValid", resourceCulture);
            }
        }
    }
}
